name: instance
channels:
  - defaults
  - nvidia
dependencies:
  - python=3.7
  - cudatoolkit=10.1.*
  - cudnn=7.6.*
  - numpy
  - scikit-image
  - jupyter
  - pip
  - pip:
    - tensorflow==2.3.*
    - csbdeep
    - stardist
    - gputools
