name: 04_instance_segmentation
channels:
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - tensorflow-gpu
  - jupyter
  - numpy
  - scikit-image
  - scikit-learn
  - pandas
  - scipy
  - seaborn
  - tqdm
  - ipython
  - pip
  - pip:
    - csbdeep
    - stardist
    - gputools
